server:
  socketPort: 8000
    frontend1StartCommand:
    dbService1StartCommand:
    frontend2StartCommand:
    dbService2StartCommand:
  frontend1StartCommand: java -jar F:\\Documents\\java\\2019-09-otus-java-Emelyanov\\hw16-MessageServer\\hw16-frontend\\target\\hw16-frontEnd-2019-09-SNAPSHOT.jar --server.port=8080 --frontendAsynchronousServiceName=frontend1AsynchronousService --frontendSynchronousServiceName=frontend1SynchronousService --dbServiceName=db1Service
  dbService1StartCommand: java -jar F:\\Documents\\java\\2019-09-otus-java-Emelyanov\\hw16-MessageServer\\hw16-dbservice\\target\\hw16-dbService-2019-09-SNAPSHOT.jar --dbServiceName=db1Service --mongoDBName=hw16a
  frontend2StartCommand: java -jar F:\\Documents\\java\\2019-09-otus-java-Emelyanov\\hw16-MessageServer\\hw16-frontend\\target\\hw16-frontEnd-2019-09-SNAPSHOT.jar --server.port=8081 --frontendAsynchronousServiceName=frontend2AsynchronousService --frontendSynchronousServiceName=frontend2SynchronousService --dbServiceName=db2Service
  dbService2StartCommand: java -jar F:\\Documents\\java\\2019-09-otus-java-Emelyanov\\hw16-MessageServer\\hw16-dbservice\\target\\hw16-dbService-2019-09-SNAPSHOT.jar --dbServiceName=db2Service --mongoDBName=hw16b
  clientsNumber: 4
  clientStartDelaySec: 5

