client:
    frontendAsynchronousServiceName: frontendAsynchronousServiceName
    frontendSynchronousServiceName: frontendSynchronousServiceName
    dbServiceName: databaseService

    hostMS: localhost
    portMS: 8000

    socketName: frontendSynchronousServiceName