client:
    frontendAsynchronousServiceName: frontend1AsynchronousService
    frontendSynchronousServiceName: frontend1SynchronousService
    dbServiceName: db1Service

    hostMS: localhost
    portMS: 8000
