server:
  socketPort: 8000
  frontendStartCommand:
  dbServiceStartCommand:
  clientsNumber: 2
  clientStartDelaySec: 5

client:
  frontendAsynchronousServiceName: frontendAsynchronousServiceName
  frontendSynchronousServiceName: frontendSynchronousServiceName
  dbServiceName: databaseService
